#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN

//#undef TAPPING_TERM
//#define TAPPING_TERM 150
//#undef COMBO_TERM
//#define COMBO_TERM 200

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define COMBO_PERMISSIVE_HOLD

#define LEADER_TIMEOUT 300

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2
