#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN

#undef TAPPING_TERM
#define TAPPING_TERM 200

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define RETRO_TAPPING

#define COMBO_PERMISSIVE_HOLD
#undef COMBO_TERM
#define COMBO_TERM 30
#define COMBO_TERM_PER_COMBO

#define LEADER_TIMEOUT 250
#define LEADER_PER_KEY_TIMING

// Maybe this is necessary...?
// #define TAP_CODE_DELAY 100

// Not supported without flto
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
